# Generated by Django 3.1.7 on 2021-03-20 01:59

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(name="Fahrur Rozzi", email="rozzi@frozz.com", document="22342342", phone="0000000").save()


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
